# Generated by Django 2.2.5 on 2019-10-11 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Cliente', models.CharField(max_length=100)),
                ('celular_Cliente', models.IntegerField(default=0)),
                ('correo_Cliente', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('linea', models.CharField(max_length=50)),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'AUTOMOVIL'), (2, 'CAMIONETA'), (3, 'PICK UP'), (4, 'MINIVAN')])),
                ('asientos', models.IntegerField(default=0)),
                ('valor', models.FloatField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizador.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Empleado', models.CharField(max_length=100)),
                ('codigo_Empleado', models.IntegerField(default=0)),
                ('iniciales', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deducible', models.FloatField(default=0)),
                ('deducible_robo', models.FloatField(default=0)),
                ('lesiones', models.IntegerField(default=0)),
                ('accidentes', models.IntegerField(default=0)),
                ('anual_valor_Seguro', models.FloatField(default=0)),
                ('semestral_valor_Seguro', models.FloatField(default=0)),
                ('trimestral_valor_Seguro', models.FloatField(default=0)),
                ('mensual_valor_Seguro', models.FloatField(default=0)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizador.Vehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cotizador.Empleado'),
        ),
    ]
