# Generated by Django 2.2.5 on 2019-09-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='deducible',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='asientos',
            field=models.IntegerField(default=0),
        ),
    ]
