# Generated by Django 2.2.5 on 2019-09-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0002_auto_20190922_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='anual_valor_Seguro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='mensual_valor_Seguro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='semestral_valor_Seguro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='trimestral_valor_Seguro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
