# Generated by Django 2.2.5 on 2019-09-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0004_auto_20190922_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='deducible_robo',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=7),
        ),
    ]
