# Generated by Django 2.2.5 on 2019-09-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0006_auto_20190929_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='deducible',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='deducible_robo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
